networks:
  public:
    external: true

services:
  readme_stats:
    build: .
    container_name: readme_stats
    env_file:
      - .env
    expose:
      - ${port}
    healthcheck:
      test: wget --no-verbose -O - --tries=1 http://localhost:$$port/?username=digitaladapt | grep 'GitHub Stats' || exit 1
      interval: 60m # hourly
      retries: 3
      start_interval: 1s
      start_period: 10s
      timeout: 5s
    init: true
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # built, disable watchtower
    networks:
      - public
    restart: always

  # allow watchtower to monitor for update to base image, since our container is built
  readme_stats_monitor:
    container_name: readme_stats_monitor
    entrypoint: "/bin/true"
    image: node:lts-alpine
    restart: no

